apiVersion: v1
kind: Service
metadata:
  name: amazon-app-service
spec:
  selector:
    app.kubernetes.io/name: amazon-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
